// <auto-generated />
namespace Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delete_column_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_column_info));
        
        string IMigrationMetadata.Id
        {
            get { return "201906041109576_delete_column_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
